### ISSUE TITLE
User Story: Navigation Bar

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#1]
Epic: Navigation and User Interface

As a User I can **navigate the site** so that **i can easily find my way to relevant pages**

**Acceptance Criteria**

- [x] Navbar is visible and functional on every page.
- [x] Links to key pages (Home, Profile, Calendar etc) work correctly.

**Tasks**

- [x] Design a consistent navbar layout.
- [x] Implement routing for navbar links.
