### ISSUE TITLE
User Story: Post Creation

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#10]
Epic: Content Creation

As a logged in user I can **create a post** so that **other users can see what i am up to**

**Acceptance Criteria**

- [x] Users can create, view, edit, and delete events.
- [x] Posts include details like image title and content,

**Tasks**

- [x] Develop a post creation form.
- [x] Implement CRUD operations for events.
