### ISSUE TITLE
User Story: Gear List Creation

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#11]
Epic: Content Creation

As a logged in user I can **create a Gear list** so that **i can keep track of my equipment and other users can see what i use in my activities**

**Acceptance Criteria**

- [x] Users can create, view, edit, and delete gear lists.
- [x] Gear lists include details like image title, category and description,

**Tasks**

- [x] Develop a gear list creation form.
- [x] Implement CRUD operations for gear lists.
