### ISSUE TITLE
User Story: Profile-based Post Display

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#12]
Epic: Content Creation

As a User I can **view all posts created by a specific user on their profile** so that **so that i can see what they want to share**

**Acceptance Criteria**

- [x] Users can view all posts created by a specific user on their profile.
- [x] Clicking on a posts redirects to its detailed page.

**Tasks**

- [x]  Fetch and display user-specific posts on their profile.
- [x] Implement routing from profile to posts pages
