### ISSUE TITLE
User Story: Profile-based Gear List Display

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#13]
Epic: Content Creation

As a User I can **view all gear lists created by a specific user on their profile** so that **so that i can see what gear other site users have**

**Acceptance Criteria**

- [x] Users can view all gear lists created by a specific user on their profile.
- [x] Clicking on a gear list redirects to its detailed page.

**Tasks**

- [x]  Fetch and display user-specific gear lists on their profile.
- [x] Implement routing from profile to gear list pages
