### ISSUE TITLE
User Story: User Sign Up

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#14]
Epic: User Account Management

As a User I can **sign up** so that **i have a log in credentials for the site **

**Acceptance Criteria**

- [ ] Users can create an account.
- [ ] Incorrect sig up details provide clear feedback.

**Tasks**

- [ ] Develop a sign up form with validation.
- [ ] Implement authentication system.
