### ISSUE TITLE
User Story: Calendar Page

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#15]
Epic: Scheduling Overview

As a User I can **click the calendar nav link** so that **i can see all events by date**

**Acceptance Criteria**

- [x] Have a calendar view
- [x] Automatically populate calendar with events

**Tasks**

- [x] Install react big calendar
- [x] Implement calendar functionality with events
