### ISSUE TITLE
User Story: Post Management

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#16]
Epic: Content Creation

As a User I can **create, view, edit, and delete posts** so that **i can keep my posts up to date and relevant**

**Acceptance Criteria**

- [x] Users can create, view, edit, and delete posts
- [x] Post changes are updated in real-time

**Tasks**

- [x] Develop UI components for creating and managing posts
- [x] Implement CRUD operations for posts
