### ISSUE TITLE
User Story:  Event Management

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#17]
Epic: Content Creation

As a User I can **create, view, edit, and delete events** so that **i can keep my events up to date**

**Acceptance Criteria**

- [x] Users can create, view, edit, and delete events
- [x] Event changes are updated in real-time

**Tasks**

- [x] Develop UI components for creating and managing events
- [x] Implement CRUD operations for events
