### ISSUE TITLE
Issue: Functionality Testing of User Stories

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#19]
Epic: Quality Assurance

**Acceptance Criteria**

- [x] Every user story's functionality is fully operational and meets defined criteria

**Tasks**

- [x] Test each user story for expected functionality
- [x] Validate the integration of different components (e.g., posts, events, gear lists)
- [x] Identify and log any functional discrepancies or bugs
