### ISSUE TITLE
User Story: Efficient Routing

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#2]
Epic: Navigation and User Interface

As a User I can **capability** so that **receieved benefit**

**Acceptance Criteria**

- [ ] Users can navigate through pages without full page reloads.
- [ ] Page transitions are smooth and quick.

**Tasks**

- [ ] Implement React Router for single-page application behavior
- [ ] Optimize load times for different components.
