### ISSUE TITLE
Issue: Backend API Testing

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#20]
Epic: Backend Development

**Acceptance Criteria**

- [ ] All API endpoints return correct data and status codes
- [ ] Error handling is properly implemented

**Tasks**

- [ ] Manually test API endpoints
- [ ] Check for correct HTTP status codes in various scenarios
- [ ] Error handling and data validation
