### ISSUE TITLE
User Story: Account Creation

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#3]
Epic: User Account Management

As a User I can **create an account** so that i **can get access to more functionality on the site**

**Acceptance Criteria**

- [x] New users can create an account.
- [x] The sign-up process is intuitive and user-friendly.

**Tasks**

- [x] Create a sign-up form with necessary fields.
- [x] Validate user input and handle account creation on the backend.
