### ISSUE TITLE
User Story: User Sign-In

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#4]
Epic: User Account Management

As a User I can **sign in to my account** so that **i can fully make use of the site **

**Acceptance Criteria**

- [x] Users can log in to their account.
- [x] Incorrect login details provide clear feedback.

**Tasks**

- [x] Develop a login form with validation.
- [x] Implement authentication system.
