### ISSUE TITLE
User Story: Authentication Feedback

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#5]
Epic: User Account Management

As a User I can **see if im logged in or out** so that **i have knowledge of my status**

**Acceptance Criteria**

- [x] Users can easily identify their login status.
- [x] Logged-in users see a different set of menu options.

**Tasks**

- [x] Display user's avatar or login/signup options based on authentication status.
- [x] Implement state management to track user authentication.
