### ISSUE TITLE
User Story: Event Creation

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#6]
Epic: Content Creation

As a User I can **create and publish an event** so that **i can get people be aware and possibly attend **

**Acceptance Criteria**

- [x] Logged-in users can create and publish events.
- [x] Events display necessary details (title, date, description)

**Tasks**

- [x] Design and implement an event creation form.
- [x] Handle event data storage and retrieval.
