### ISSUE TITLE
User Story: Event Calendar Interaction

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#7]
Epic: Content Creation

As a User I can **see published events in the calendar** so that **i can get a timeline overview and plan accordingly**

**Acceptance Criteria**

- [x] Events are visible in a calendar view.
- [x] Users can click on events to view more details.

**Tasks**

- [x] Integrate a calendar component.
- [x] Link events in the calendar to their detailed view pages.
