### ISSUE TITLE
User Story: Profile-based Event Display

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#8]
Epic: Content Creation

As a User I can **view all events created by a specific user on their profile** so that **i can see what other site users are up to**

**Acceptance Criteria**

- [ ] Users can view all events created by a specific user on their profile.
- [ ] Clicking on an event redirects to its detailed page.

**Tasks**

- [ ] Fetch and display user-specific events on their profile.
- [ ] Implement routing from profile to event pages
