### ISSUE TITLE
User Story: Gear List Management

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/hbc-frontend#9]
Epic: Content Creation

As a User I can **create, view, edit, and delete gear lists** so that **i can keep my lists up to date as my equipment changes**

**Acceptance Criteria**

- [x] Users can create, view, edit, and delete gear lists.
- [x] Gear list changes are updated in real-time.

**Tasks**

- [x] Develop UI components for creating and managing gear lists.
- [x] Implement CRUD operations for gear lists.
